export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';

export const LOAD_LIST_ORDER_SUCCESS = 'LOAD_LIST_ORDER_SUCCESS';
export const MOVE_LIST = 'MOVE_LIST';
export const MOVE_CARD = 'MOVE_CARD';
export const TOGGLE_DRAGGING = 'TOGGLE_DRAGGING';
