# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustonlam_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('finished', 'Finished')], default='new', max_length=10),
        ),
    ]
