# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustonlam_apps', '0002_auto_20171009_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='finish_time',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
