# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustonlam_apps', '0003_orders_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
