# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustonlam_apps', '0004_auto_20171010_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_key',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
