# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hustonlam_apps', '0005_orders_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
